CREATE TABLE DOCUMENT_TYPE
(
    IDENTIFIER VARCHAR(255) NOT NULL,
    NAME       VARCHAR(255) NOT NULL,
    PRIMARY KEY (IDENTIFIER)
);

CREATE TABLE FOLDER_TEMPLATE
(
    IDENTIFIER               VARCHAR(255) NOT NULL,
    NAME                     VARCHAR(255) NOT NULL,
    PARENT_FOLDER            VARCHAR(255),
    ASSOCIATED_DOCUMENT_TYPE VARCHAR(255),
    PRIMARY KEY (IDENTIFIER),
    FOREIGN KEY (PARENT_FOLDER) REFERENCES FOLDER_TEMPLATE (IDENTIFIER),
    FOREIGN KEY (ASSOCIATED_DOCUMENT_TYPE) REFERENCES DOCUMENT_TYPE (IDENTIFIER)
);

CREATE TABLE FOLDER
(
    IDENTIFIER               VARCHAR(255) NOT NULL,
    TEMPLATE                 VARCHAR(255) NOT NULL,
    NAME                     VARCHAR(255) NOT NULL,
    PARENT_FOLDER            VARCHAR(255),
    ASSOCIATED_DOCUMENT_TYPE VARCHAR(255),
    PRIMARY KEY (IDENTIFIER),
    FOREIGN KEY (PARENT_FOLDER) REFERENCES FOLDER (IDENTIFIER),
    FOREIGN KEY (TEMPLATE) REFERENCES FOLDER_TEMPLATE (IDENTIFIER),
    FOREIGN KEY (ASSOCIATED_DOCUMENT_TYPE) REFERENCES DOCUMENT_TYPE (IDENTIFIER)
);

CREATE TABLE DOCUMENT
(
    IDENTIFIER              VARCHAR(255) NOT NULL,
    NAME                    VARCHAR(255) NOT NULL,
    PARENT_FOLDER           VARCHAR(255),
    TYPE           VARCHAR(255),
    PREDICTED_TYPE VARCHAR(255),
    PRIMARY KEY (IDENTIFIER),
    FOREIGN KEY (PARENT_FOLDER) REFERENCES FOLDER (IDENTIFIER),
    FOREIGN KEY (TYPE) REFERENCES DOCUMENT_TYPE (IDENTIFIER),
    FOREIGN KEY (PREDICTED_TYPE) REFERENCES DOCUMENT_TYPE (IDENTIFIER)
);
