CREATE TABLE DOCUMENT_TYPE
(
    IDENTIFIER VARCHAR(255) NOT NULL,
    NAME       VARCHAR(255) NOT NULL,
    PRIMARY KEY (IDENTIFIER)
);

CREATE TABLE FOLDER_TEMPLATE
(
    IDENTIFIER                          VARCHAR(255) NOT NULL,
    NAME                                VARCHAR(255) NOT NULL,
    PARENT_FOLDER_IDENTIFIER            VARCHAR(255),
    ASSOCIATED_DOCUMENT_TYPE_IDENTIFIER VARCHAR(255),
    PRIMARY KEY (IDENTIFIER),
    FOREIGN KEY (PARENT_FOLDER_IDENTIFIER) REFERENCES FOLDER_TEMPLATE (IDENTIFIER),
    FOREIGN KEY (ASSOCIATED_DOCUMENT_TYPE_IDENTIFIER) REFERENCES DOCUMENT_TYPE (IDENTIFIER)
);

CREATE TABLE FOLDER
(
    IDENTIFIER                          VARCHAR(255) NOT NULL,
    TEMPLATE_IDENTIFIER                 VARCHAR(255) NOT NULL,
    NAME                                VARCHAR(255) NOT NULL,
    PARENT_FOLDER_IDENTIFIER            VARCHAR(255),
    ASSOCIATED_DOCUMENT_TYPE_IDENTIFIER VARCHAR(255),
    PRIMARY KEY (IDENTIFIER),
    FOREIGN KEY (PARENT_FOLDER_IDENTIFIER) REFERENCES FOLDER (IDENTIFIER),
    FOREIGN KEY (TEMPLATE_IDENTIFIER) REFERENCES FOLDER_TEMPLATE (IDENTIFIER),
    FOREIGN KEY (ASSOCIATED_DOCUMENT_TYPE_IDENTIFIER) REFERENCES DOCUMENT_TYPE (IDENTIFIER)
);

CREATE TABLE DOCUMENT
(
    IDENTIFIER                VARCHAR(255) NOT NULL,
    NAME                      VARCHAR(255) NOT NULL,
    PARENT_FOLDER_IDENTIFIER  VARCHAR(255),
    TYPE_IDENTIFIER           VARCHAR(255),
    PREDICTED_TYPE_IDENTIFIER VARCHAR(255),
    PRIMARY KEY (IDENTIFIER),
    FOREIGN KEY (PARENT_FOLDER_IDENTIFIER) REFERENCES FOLDER (IDENTIFIER),
    FOREIGN KEY (TYPE_IDENTIFIER) REFERENCES DOCUMENT_TYPE (IDENTIFIER),
    FOREIGN KEY (PREDICTED_TYPE_IDENTIFIER) REFERENCES DOCUMENT_TYPE (IDENTIFIER)
);
