spring:
  graphql:
    graphiql:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/papyrus
    username: toth
    password: parchment

  liquibase:
    change-log: classpath:db/changelog/changelog.yml
    enabled: true

springdoc:
  swagger-ui:
    path: /api-docs

papyrus:
  cloud:
    topic: papyrus
    queue: documents-uploaded
    bucket: io.alexandria.papyrus.codex

management:
  endpoints:
    web:
      exposure:
        include: health,info
